version: '3'
services:
  app:
    build: .
    entrypoint: go run main.go
    ports:
     - "7000:8080"
    volumes:
      - "./app:/app"
    depends_on: 
     - redis
  redis:
    image: "redis:alpine"

  adminer:
    image: adminer
    ports:
    - 8085:8080

  db-price:
    image: mysql:8.0.30
    command: --innodb-use-native-aio=0
    restart: always
    tty: true
    ports:
      - "3306"
    volumes:
      - "./mysql/dbdata:/var/lib/mysql"
    environment:
      MYSQL_DATABASE: price_db
      MYSQL_ROOT_PASSWORD: root